config/routes.rb
Ak::Application.routes.draw do
  resources :depots, except: :show
  resources :items, except: :destroy
  resources :units, except: :destroy
  resources :projects do
    resources :plans
    resources :currents
    collection do
      get "i18n"
    end
  end
  devise_for :users
  root 'pages#index'
  match '/depotsum', to: 'pages#depotsum', via: 'get'
  match '/itemsum',  to: 'pages#itemsum',  via: 'get'
  get '/projects/:id/projsum', to: 'projects#projsum', as: 'projsum'
  match '/about',   to: 'pages#about',   via: 'get'
  match '/contact',   to: 'pages#contact',   via: 'get'
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :plans, dependent: :destroy
  has_many :items, through: :plans

  has_many :currents, dependent: :destroy
  has_many :items, through: :currents
  validates :name, presence: true, uniqueness: true
  validates :user_id, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!
  before_action :find_proj, :only => [:show, :edit, :update, :destroy, :projsum]

  def index
    @projects = current_user.projects
  end

  def show
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user

    if @project.save
      redirect_to projects_url, notice: 'A projekt sikeresen létrehozva.'
    else
      render action: 'new'
    end
  end

  def update
    if @project.update(project_params)
      redirect_to projects_url, notice: 'A projekt adatait sikeresen frissítette.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'A projekt törölve.'
  end

  def i18n
    locale = {
        "sProcessing" =>  "Dolgozunk...",
        "sLengthMenu" =>  "_MENU_ sort mutasson oldalanként",
        "sZeroRecords" => "Adatok nincsenek",
        "sInfo" =>         "  _TOTAL_ sor van összesen, _START_ - _END_ sorok láthatóak most",
        "sInfoEmpty"  =>   "Nincs adat",
        "sInfoFiltered" => "(az adatok amiket most lát szűrtek, _MAX_ sor van összesen)",
        "sInfoPostFix" =>  "",
        "sSearch" =>       "Keresés:",
        "sUrl" =>          "",
        "oPaginate" => {
          "sFirst"  =>   "Első",
          "sPrevious" => "Előző",
          "sNext" =>    "Következő",
          "sLast" =>   "Utolsó"
        }
    }

    render :json => locale
  end

  def projsum
  end

  private
    def find_proj
      @project = current_user.projects.find(params[:id])
      rescue ActiveRecord::RecordNotFound
      redirect_to projects_path, :flash => { :error => "A projekt nem található." }
    end

    def project_params
      params.require(:project).permit(:name, :description, :user_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def filtered_currents
    tank = Current.where(:project_id => @project.id)
    currents = tank.group("item_id")
    @filtered_currents = currents.select("item_id, sum(quantity) as total_quantity")
  end

  def filtered_plans
    storage = Plan.where(:project_id => @project.id)
    plans = storage.group("item_id")
    @filtered_plans = plans.select("item_id, sum(quantity) as total_quantity")
  end
end

app/views/projects/_form.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="panel panel-primary">
       <div class="panel-heading">
        <% if @project.new_record? %>
          <h3>Projekt létrehozása</h3>
        <% else %>
          <h3>Projekt szerkesztése</h3>
        <% end %>
      </div>
      <div class="panel-body">
        <%= form_for(@project) do |f| %>
          <% if @project.errors.any? %>
            <div id="error_explanation">
              <h2><%= @project.errors.count %> hibát kérem javítson ki:</h2>

              <ul>
              <% @project.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          <div class="field">
            <%= f.label :name, "A projekt neve" %>  
            <%= f.text_field :name, :autofocus => true, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :description, "A projekt adatai" %> 
            <%= f.text_area :description, :rows => "10", class: 'form-control' %>
          </div>
          <% if @project.new_record? %>
            <%= f.submit "Projekt létrehozása", class: 'btn btn-primary btn-lg btn-block' %>
          <% else %>
            <%= f.submit "Projekt adatok frissítése", class: 'btn btn-primary btn-lg btn-block' %>
          <% end %>
        <% end %>
      </div> <!--panel-body -->
    </div> <!--panel-primary -->
  </div> <!--col-md4 -->
</div> <!--row -->

app/views/projects/edit.html.erb
<% provide(:oldal_cim, 'AK-Projekt szerkesztése') %>

<%= render 'form' %>

app/views/projects/index.html.erb
<% provide(:oldal_cim, 'AK-Projektek') %>
<h1>Projektek</h1>

<table class="table">
  <tr>
    <th>A projekt neve</th>
    <th>A projekt adatai</th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= link_to project.name, project_path(project) %></td>
    <td><%= truncate(project.description, :length => 70, :separator => ' ' ) %></td>
    <td><%= link_to 'Projekt név és leírás szerkesztése', edit_project_path(project) %></td>
    <td><%= link_to 'Projekt törlése', project, method: :delete, data: { confirm: 'Biztosan törlöd a projektet?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Új projekt', new_project_path, class: "btn btn-primary" %>

app/views/projects/new.html.erb
<% provide(:oldal_cim, 'AK-Projekt létrehozása') %>

<%= render 'form' %>

app/views/projects/projsum.html.erb
<% provide(:oldal_cim, 'AK-Projekt összesítő') %>

<div class="well">
  <h2>
    <%= @project.name + ' - anyagkimutatás' %>
  </h2>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <h4>TERVEZETT ANYAGOK</h4>
      </div>
    </div>
    <table class="table">
      <tbody>
        <% filtered_plans.each do |fipla| %>
          <tr>
            <td><%= fipla.item.name %></td>
            <% sign = 1 %>
              <% filtered_currents.each do |current| %>
                  <% if fipla.item.name == current.item.name %>
                    <% if fipla.total_quantity > current.total_quantity %>
                      <td style="color: green;"><%= "A beszállított mennyiség még nem érte el a tervezettett!"  %></td>    
                    <% elsif fipla.total_quantity < current.total_quantity %>
                      <td style="color: red;"><%= "A tervezett mennyiség meghaladva: " + (current.total_quantity - fipla.total_quantity).to_s + ' ' + fipla.item.unit.name + " többlet beszállítás történt az anyagból!"  %></td>
                    <% elsif %>
                      <td style="color: green;"><%= "A tervezett mennyiség, azaz " + fipla.total_quantity.to_s + ' ' + fipla.item.unit.name + " van jelenleg beszállítva."  %></td>
                    <% end %>  
                    <% sign = 2 %>
                  <% end %>
              <% end %>
              <% if sign == 1 %>
                <td style="color: blue;"><%= "A munkahelyre még nem lett beszállítva ebből az anyagból!"  %></td>
              <% end %>
          </tr>
        <% end %>  
      </tbody>
    </table>
  </div>

  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-body" style="background-color: #d99395;">
        AZ ELŐRE NEM TERVEZETT ANYAGOK
      </div>
    </div>
    <table class="table">
      <tbody>
        <% filtered_currents.each do |ficu| %>
          <% sign = 1 %>
            <% filtered_plans.each do |fipa| %>
              <% if ficu.item.name == fipa.item.name %>    
                <% sign = 2 %>
              <% end %>
            <% end %>
            <% if sign == 1 %>
              <tr>
                <td><%= ficu.item.name %></td>
                <td><%= ficu.total_quantity.to_s + ' ' + ficu.item.unit.name %></td>
                <td><%= "Ez a beszállított anyag nem volt tervezve." %></td>
              </tr>
            <% end %>
        <% end %>  
      </tbody>
    </table>
  </div>
    
</div>

<p>
  <%= link_to 'Visszalépés a projekthez', project_path(@project), class: 'btn btn-default btn-xs' %>
</p>

app/views/projects/show.html.erb
<% provide(:oldal_cim, 'AK-Projekt adatok') %>
<p id="notice"><%= notice %></p>

<div class="well">
  <h2>
    <%= @project.name + ' - beszállított anyagok' %>
  </h2>
</div>

<table id="currents" class="table">
  <thead>
    <tr>
      <th>Anyag neve</th>
      <th>Mennyisége</th>
      <th>Mennyiségi egysége</th>
      <th>Bizonylat</th>
      <th>Beszállítás dátuma</th>
      <th>Sor törlése</th>
    </tr>
  </thead>
  <tbody>
    <% @project.currents.each do |current| %>
      <tr>
        <td><%= link_to current.item.name, edit_project_current_path(@project, current) %>
        <td><%= current.quantity  %></td>
        <td><%= current.item.unit.name  %></td>
        <td><%= current.pass %> </td>
        <td><%= current.delivery %> </td>
        <td><%= link_to 'Sor törlése', project_current_path(@project, current), method: :delete, data: { confirm: 'Biztosan törlöd a sort?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'Anyag beszállítás', new_project_current_path(@project), class: "btn btn-primary" %> <hr>
<%= link_to 'Tervezett anyagfelhasználás', project_plans_path(@project), class: "btn btn-default btn-xs" %>
<%= link_to 'Anyag raktározás', new_depot_path, class: "btn btn-default btn-xs" %>
<%= link_to 'Projekt kimutatás', projsum_path, class: "btn btn-default btn-xs" %>