config/routes.rb
Ak::Application.routes.draw do
  resources :depots, except: :show
  resources :items, except: :destroy
  resources :units, except: :destroy
  resources :projects do
    resources :plans
    resources :currents
    collection do
      get "i18n"
    end
  end
  devise_for :users
  root 'pages#index'
  match '/depotsum', to: 'pages#depotsum', via: 'get'
  match '/itemsum',  to: 'pages#itemsum',  via: 'get'
  get '/projects/:id/projsum', to: 'projects#projsum', as: 'projsum'
  match '/about',   to: 'pages#about',   via: 'get'
  match '/contact',   to: 'pages#contact',   via: 'get'
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_many :items
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  def index
    @units = Unit.all
  end

  def show
  end

  def new
    @unit = Unit.new
  end

  def edit
  end

  def create
    @unit = Unit.new(unit_params)

    if @unit.save
      redirect_to units_url, notice: 'A mértékegység sikeresen létrehozva.'
    else
      render action: 'new'
    end
  end

  def update
    if @unit.update(unit_params)
      redirect_to units_url, notice: 'A mértékegység sikeresen szerkesztve.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @unit.destroy
    redirect_to units_url, notice: 'Unit was successfully destroyed.'
  end

  private
    def set_unit
      @unit = Unit.find(params[:id])
    end

    def unit_params
      params.require(:unit).permit(:name)
    end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="panel panel-primary">
       <div class="panel-heading">
        <% if @unit.new_record? %>
          <h3>Mértékegység létrehozása</h3>
        <% else %>
          <h3>Mértékegység szerkesztése</h3>
        <% end %>
      </div>
      <div class="panel-body">
        <%= form_for(@unit) do |f| %>
          <% if @unit.errors.any? %>
            <div id="error_explanation">
              <h2><%= @unit.errors.count %> hibát kérem javítson ki:</h2>

              <ul>
              <% @unit.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          <div class="field">
            <%= f.label :name, "A mértékegység neve" %>  
            <%= f.text_field :name, :autofocus => true, class: 'form-control' %>
          </div>
          <div class="form-group">
          </div>
          <% if @unit.new_record? %>
            <%= f.submit "Mértékegység létrehozása", class: 'btn btn-primary btn-lg btn-block' %>
          <% else %>
            <%= f.submit "Mértékegység frissítése", class: 'btn btn-primary btn-lg btn-block' %>
          <% end %>
        <% end %>
      </div> <!--panel-body -->
    </div> <!--panel-primary -->
  </div> <!--col-md4 -->
</div> <!--row -->

app/views/units/edit.html.erb
<% provide(:oldal_cim, 'AK-Mértékegység szerkesztése') %>

<%= render 'form' %>

<%= link_to 'Visszalépés', units_path %>

app/views/units/index.html.erb
<% provide(:oldal_cim, 'AK-Mértékegységek') %>

<h1>Mértékegységek</h1>

<table class="table table-condensed">
  <tr>
    <th>Mértékegység neve</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @units.each do |unit| %>
  <tr>
    <td><%= unit.name %></td>
    <td><%= link_to 'Mértékegység szerkesztése', edit_unit_path(unit) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Új mértékegység', new_unit_path, class: "btn btn-primary" %>

app/views/units/new.html.erb
<% provide(:oldal_cim, 'AK-Új mértékegység létrehozása') %>

<%= render 'form' %>

<%= link_to 'Visszalépés', units_path %>

app/views/units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Mértékegység neve:</b>
  <%= @unit.name %>
</p>

<%= link_to 'Visszalépés', units_path %>