config/routes.rb
Ak::Application.routes.draw do
  resources :depots, except: :show
  resources :items, except: :destroy
  resources :units, except: :destroy
  resources :projects do
    resources :plans
    resources :currents
    collection do
      get "i18n"
    end
  end
  devise_for :users
  root 'pages#index'
  match '/depotsum', to: 'pages#depotsum', via: 'get'
  match '/itemsum',  to: 'pages#itemsum',  via: 'get'
  get '/projects/:id/projsum', to: 'projects#projsum', as: 'projsum'
  match '/about',   to: 'pages#about',   via: 'get'
  match '/contact',   to: 'pages#contact',   via: 'get'
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  belongs_to :project
  belongs_to :item
  validates :item_id, presence: :true
  validates :quantity, presence: :true
  validates_numericality_of :quantity, greater_than: 0
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_project, only: [:index, :new, :edit, :create, :update, :destroy]
  before_action :set_plan, only: [:edit, :update, :destroy]
  
  def index
    @project.plans.collect
  end

  def new
    @plan = @project.plans.build
  end

  def edit
    @plan = @project.plans.find(@plan.id)
  end

  def create
    @plan = Plan.new(plan_params)
    @plan.project_id =  @project.id
    if @project.plans.where(:item_id => @plan.item_id).blank?
      @plan.save
      redirect_to project_plans_url
    elsif
      @plan.quantity.nil?
      redirect_to project_plans_url, :flash => { :error => "Nem megfelelő adatot adott meg!" }
    else  
      new_plan = @project.plans.where(item_id: @plan.item_id).first_or_initialize
      new_plan.quantity += @plan.quantity
      new_plan.save
      redirect_to project_plans_url
    end
  end

  def update
    if @plan.update(plan_params)
      redirect_to project_plans_url, notice: 'A sor sikeresen szerkesztve.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @plan.destroy
    redirect_to project_plans_url, notice: 'A sor törölve.'
  end

private
  def set_project
    @project = current_user.projects.find(params[:project_id])
    rescue ActiveRecord::RecordNotFound
      redirect_to projects_path, :flash => { :error => "A projekt nem található." }
  end

  def plan_params
    params.require(:plan).permit(:item_id, :quantity)
  end

  def set_plan
    @plan = @project.plans.find(params[:id])
  end  
end

app/views/plans/_form.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="panel panel-primary">
       <div class="panel-heading">
        <% if @plan.new_record? %>
          <h3>
            <%= @project.name %></br>
            <span class="glyphicon glyphicon-plus"></span></br>
            <%= 'Tervezett anyag sor felvitele' %>
          </h3>
        <% else %>
          <h3>
            <%= @project.name %></br>
            <span class="glyphicon glyphicon-pencil"></span></br>
            <%= 'Tervezett anyag sor módosítása' %>
          </h3>
        <% end %>
      </div>
      <div class="panel-body">
        <%= simple_form_for [@project, @plan] do |f| %>
          <% if @project.errors.any? %>
            <div id="error_explanation">
              <h2><%= @project.errors.count %> hibát kérem javítson ki:</h2>

              <ul>
              <% @project.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          <% if @plan.new_record? %>
            <div class="field">
              <%= f.association :item, label: 'A tervezett anyag neve', :autofocus => true, include_blank: false %>
            </div>
          <% else %>
            <h4><%= @plan.item.name %></h4>
          <% end %>
          </br>
          <div class="field">
            <%= f.input :quantity, as: :decimal, label: 'Mennyiség a tervezett anyagból' %>
          </div>
          </br>
          <% if @plan.new_record? %>
            <%= f.submit "Anyag sor létrehozása", class: 'btn btn-primary btn-lg btn-block' %>
          <% else %>
            <%= f.submit "Anyag sor frissítése", class: 'btn btn-primary btn-lg btn-block' %>
          <% end %>
        <% end %>
      </div> <!--panel-body -->
    </div> <!--panel-primary -->
  </div> <!--col-md4 -->
</div> <!--row -->

app/views/plans/edit.html.erb
<% provide(:oldal_cim, 'AK-Tervezett anyag szerkesztése') %>

<%= render 'form' %>

app/views/plans/index.html.erb
<% provide(:oldal_cim, 'AK-Tervezett anyagfelhasználás') %>

<div class="well">
  <h2>
    <%= @project.name + ' - tervezett anyagfelhasználása' %>
  </h2>
</div>

<table class="table">
  <tbody>
    <% @project.plans.each do |plan| %>
      <tr>
        <td><%= plan.item.name + ' :  '%><strong><%= (plan.quantity).to_s + ' ' + plan.item.unit.name %></strong> </td>
        <td><%= link_to 'Sor szerkesztése', edit_project_plan_path(@project, plan) %></td>
        <td><%= link_to 'Sor törlése', project_plan_path(@project, plan), method: :delete, data: { confirm: 'Biztosan törlöd a sort?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
  <%= link_to 'Anyag hozzáadása', new_project_plan_path, class: 'btn btn-primary' %>
  <%= link_to 'Visszalépés a projekthez', project_path(@project), class: 'btn btn-default btn-xs' %>
</p>

app/views/plans/new.html.erb
<% provide(:oldal_cim, 'AK-Új tervezett anyag') %>

<%= render 'form' %>