config/routes.rb
Ak::Application.routes.draw do
  resources :depots, except: :show
  resources :items, except: :destroy
  resources :units, except: :destroy
  resources :projects do
    resources :plans
    resources :currents
    collection do
      get "i18n"
    end
  end
  devise_for :users
  root 'pages#index'
  match '/depotsum', to: 'pages#depotsum', via: 'get'
  match '/itemsum',  to: 'pages#itemsum',  via: 'get'
  get '/projects/:id/projsum', to: 'projects#projsum', as: 'projsum'
  match '/about',   to: 'pages#about',   via: 'get'
  match '/contact',   to: 'pages#contact',   via: 'get'
end

app/views/layouts/_lablec.html.erb
<hr>
<div class="row">
  <div class="col-md-3">
    <a><%= link_to 'Az alkalmazásról', about_path %></a>
    <a><%= link_to 'Kapcsolat', contact_path %></a>
  </div>
  <div class="col-md-3 col-md-offset-6">
    <p class="text-right">Készítette: Balogh István</p>
  </div>
</div>

app/views/layouts/_menusor.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">AnyagKövető</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Projektek <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% user_projects.each do |project| %>
                  <li><%= link_to project.name, project_path(project) %></li>
                <% end %>
                <li class="divider"></li>
                <li><%= link_to "Összes projekt", projects_path %></li>
              </ul>
          </li>
          <li><%= link_to "Raktár", depots_path %></li>
          <li><%= link_to "Anyagok", items_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Kimutatások<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Raktári anyagok összesítése", depotsum_path %></li>
                <li><%= link_to "Az anyagok száma a rendszerben", itemsum_path %></li>
              </ul>
          </li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav  navbar-right">
        <% if user_signed_in? %>
          <p class="navbar-text"><%= link_to current_user.email + " bejelentkezve", edit_user_registration_path %></p>
          <li><%= link_to "Kijelentkezés", destroy_user_session_path, method: "delete" %></li>
        <% else %>
          <li><%= link_to "Bejelentkezés", new_user_session_path %></li>
           <li><%= link_to "Regisztráció", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%= yield(:oldal_cim) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/menusor' %>
  <div class="container">
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
      <% end %>
    <% end %>
    <%= yield %>
    <%= render 'layouts/lablec' %>
  </div>
</body>
</html>